linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - cyclop
    - gocognit
    - gocyclo
    - maintidx
    - gocritic
    - ineffassign
    # - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - funlen
    # - gci
    # - gochecknoglobals
    # - gochecknoinits
    - goconst
    # - lll
    - containedctx
    - nilnil
    - nosprintfhostport
    - prealloc
    - promlinter
    - grouper
    - tenv
    - varnamelen
    - importas
    - forcetypeassert
    - decorder
    - errname
    - execinquery
    - goerr113
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - predeclared
    - unconvert
    - wsl
    - whitespace
    - revive
    - testpackage
    - paralleltest
    - thelper
linters-settings:
errcheck:
    check-type-assertions: true
    check-blank: false # 不开启_错误检查
errorlint:
    errorf: true
exhaustive:
    check-generated: false
    default-signifies-exhaustive: false
funlen:
    lines: 65
    statements: 40
gci:
    sections:
      - standard
      - default
      - prefix(cos/lobbyplatform)