name: User interface test
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - name: Set up environment
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.ci.yml"

      - name: Install dependencies
        run: go mod tidy

      - name: Build target
        run: make user

      - name: Run local server
        run: nohup sh ./output/user/bootstrap.sh > nohup.out 2> nohup.err < /dev/null &

      - name: Test interfaces
        run: cd test && go test -v ./...