name: Interface Test

on:
  push:
    branches:
      - main
  pull_request:
    breanches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - name: Install dependencies
        run: go mod tidy

      - name: Build target
        run: make user

      - name: Archive production
        uses: actions/upload-artifact@v3
        with:
          name: build-output-all
          path: output

  test-user:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download production
        uses: actions/download-artifact@v3
        with:
          name: build-output-all

      - name: Set up environment
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.ci.yml"

      - name: Run local server
        run: nohup sh ./output/user/bootstrap.sh > nohup.out 2> nohup.err < /dev/null &

      - name: Test interfaces
        run: go test -v ./test/...

  test-video:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download production
        uses: actions/download-artifact@v3
        with:
          name: build-output-all

      - name: Set up environment
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.ci.yml"

      - name: Run local server
        run: nohup sh ./output/user/bootstrap.sh > nohup.out 2> nohup.err < /dev/null &

      - name: Test interfaces
        run: go test -v ./test/...